site_name: Mine Design Help Guide
site_url: https://example.com/
nav:
    - Introduction: index.md
    - User Registration: registration.md
    - Setting Up a Project: projectsetup.md
    - Mine Design Core Module: Project Window.md
theme: readthedocs    
